//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.5.2.0")]
[assembly: global::System.Reflection.AssemblyCopyrightAttribute("Copyright © 2008 Brian Peek (www.brianpeek.com)")]
[assembly: global::System.Reflection.AssemblyCompanyAttribute("Brian Peek (www.brianpeek.com)")]
[assembly: global::System.Reflection.AssemblyProductAttribute("WiimoteMSRS")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("WiimoteMSRS")]
[assembly: global::System.Reflection.AssemblyDescriptionAttribute("Microsoft Robotics Studio Service for the Nintendo Wiimote")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="Wiimote.Y2007.M06, Version=1.5.2.0, Culture=neutral, PublicKeyToken=21bd729cd9834" +
    "f06")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.AllowPartiallyTrustedCallersAttribute()]

namespace Dss.Transforms.TransformWiimote {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.WiimoteState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_WiimoteState_TO_WiimoteLib_WiimoteState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.WiimoteState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_WiimoteState_TO_WiimoteLib_Proxy_WiimoteState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.AccelCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_AccelCalibrationInfo_TO_WiimoteLib_AccelCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.AccelCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_AccelCalibrationInfo_TO_WiimoteLib_Proxy_AccelCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.AccelState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_AccelState_TO_WiimoteLib_AccelState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.AccelState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_AccelState_TO_WiimoteLib_Proxy_AccelState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.Point3), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_Point3_TO_WiimoteLib_Point3));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.Point3), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Point3_TO_WiimoteLib_Proxy_Point3));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.Point3F), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_Point3F_TO_WiimoteLib_Point3F));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.Point3F), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Point3F_TO_WiimoteLib_Proxy_Point3F));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.ButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_ButtonState_TO_WiimoteLib_ButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.ButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_ButtonState_TO_WiimoteLib_Proxy_ButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.IRState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_IRState_TO_WiimoteLib_IRState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.IRState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_IRState_TO_WiimoteLib_Proxy_IRState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.IRSensor), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_IRSensor_TO_WiimoteLib_IRSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.IRSensor), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_IRSensor_TO_WiimoteLib_Proxy_IRSensor));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.Point), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_Point_TO_WiimoteLib_Point));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.Point), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Point_TO_WiimoteLib_Proxy_Point));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.PointF), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.PointF), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.NunchukState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_NunchukState_TO_WiimoteLib_NunchukState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.NunchukState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_NunchukState_TO_WiimoteLib_Proxy_NunchukState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.NunchukCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_NunchukCalibrationInfo_TO_WiimoteLib_NunchukCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.NunchukCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_NunchukCalibrationInfo_TO_WiimoteLib_Proxy_NunchukCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.ClassicControllerState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_ClassicControllerState_TO_WiimoteLib_ClassicControllerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.ClassicControllerState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_ClassicControllerState_TO_WiimoteLib_Proxy_ClassicControllerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.ClassicControllerCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_ClassicControllerCalibrationInfo_TO_WiimoteLib_ClassicControllerCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.ClassicControllerCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_ClassicControllerCalibrationInfo_TO_WiimoteLib_Proxy_ClassicControllerCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.ClassicControllerButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_ClassicControllerButtonState_TO_WiimoteLib_ClassicControllerButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.ClassicControllerButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_ClassicControllerButtonState_TO_WiimoteLib_Proxy_ClassicControllerButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.GuitarState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_GuitarState_TO_WiimoteLib_GuitarState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.GuitarState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_GuitarState_TO_WiimoteLib_Proxy_GuitarState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.GuitarButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_GuitarButtonState_TO_WiimoteLib_GuitarButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.GuitarButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_GuitarButtonState_TO_WiimoteLib_Proxy_GuitarButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.GuitarFretButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_GuitarFretButtonState_TO_WiimoteLib_GuitarFretButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.GuitarFretButtonState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_GuitarFretButtonState_TO_WiimoteLib_Proxy_GuitarFretButtonState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.DrumsState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_DrumsState_TO_WiimoteLib_DrumsState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.DrumsState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_DrumsState_TO_WiimoteLib_Proxy_DrumsState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.LEDState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_LEDState_TO_WiimoteLib_LEDState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.LEDState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_LEDState_TO_WiimoteLib_Proxy_LEDState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.RumbleRequest), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_RumbleRequest_TO_WiimoteLib_RumbleRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.RumbleRequest), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_RumbleRequest_TO_WiimoteLib_Proxy_RumbleRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.BalanceBoardState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_BalanceBoardState_TO_WiimoteLib_BalanceBoardState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.BalanceBoardState), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_BalanceBoardState_TO_WiimoteLib_Proxy_BalanceBoardState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.BalanceBoardCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_BalanceBoardCalibrationInfo_TO_WiimoteLib_BalanceBoardCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.BalanceBoardCalibrationInfo), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_BalanceBoardCalibrationInfo_TO_WiimoteLib_Proxy_BalanceBoardCalibrationInfo));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.BalanceBoardSensors), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_BalanceBoardSensors_TO_WiimoteLib_BalanceBoardSensors));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.BalanceBoardSensors), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_BalanceBoardSensors_TO_WiimoteLib_Proxy_BalanceBoardSensors));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::WiimoteLib.Proxy.BalanceBoardSensorsF), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_Proxy_BalanceBoardSensorsF_TO_WiimoteLib_BalanceBoardSensorsF));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::WiimoteLib.BalanceBoardSensorsF), new global::Microsoft.Dss.Core.Attributes.Transform(WiimoteLib_BalanceBoardSensorsF_TO_WiimoteLib_Proxy_BalanceBoardSensorsF));
        }
        
        public static object WiimoteLib_Proxy_WiimoteState_TO_WiimoteLib_WiimoteState(object transformFrom) {
            global::WiimoteLib.WiimoteState target = new global::WiimoteLib.WiimoteState();
            global::WiimoteLib.Proxy.WiimoteState from = ((global::WiimoteLib.Proxy.WiimoteState)(transformFrom));
            target.AccelCalibrationInfo = ((global::WiimoteLib.AccelCalibrationInfo)(WiimoteLib_Proxy_AccelCalibrationInfo_TO_WiimoteLib_AccelCalibrationInfo(from.AccelCalibrationInfo)));
            target.AccelState = ((global::WiimoteLib.AccelState)(WiimoteLib_Proxy_AccelState_TO_WiimoteLib_AccelState(from.AccelState)));
            target.ButtonState = ((global::WiimoteLib.ButtonState)(WiimoteLib_Proxy_ButtonState_TO_WiimoteLib_ButtonState(from.ButtonState)));
            target.IRState = ((global::WiimoteLib.IRState)(WiimoteLib_Proxy_IRState_TO_WiimoteLib_IRState(from.IRState)));
            target.BatteryRaw = from.BatteryRaw;
            target.Battery = from.Battery;
            target.Rumble = from.Rumble;
            target.Extension = from.Extension;
            target.ExtensionType = ((global::WiimoteLib.ExtensionType)(((long)(from.ExtensionType))));
            target.NunchukState = ((global::WiimoteLib.NunchukState)(WiimoteLib_Proxy_NunchukState_TO_WiimoteLib_NunchukState(from.NunchukState)));
            target.ClassicControllerState = ((global::WiimoteLib.ClassicControllerState)(WiimoteLib_Proxy_ClassicControllerState_TO_WiimoteLib_ClassicControllerState(from.ClassicControllerState)));
            target.GuitarState = ((global::WiimoteLib.GuitarState)(WiimoteLib_Proxy_GuitarState_TO_WiimoteLib_GuitarState(from.GuitarState)));
            target.DrumsState = ((global::WiimoteLib.DrumsState)(WiimoteLib_Proxy_DrumsState_TO_WiimoteLib_DrumsState(from.DrumsState)));
            target.LEDState = ((global::WiimoteLib.LEDState)(WiimoteLib_Proxy_LEDState_TO_WiimoteLib_LEDState(from.LEDState)));
            return target;
        }
        
        public static object WiimoteLib_WiimoteState_TO_WiimoteLib_Proxy_WiimoteState(object transformFrom) {
            global::WiimoteLib.Proxy.WiimoteState target = new global::WiimoteLib.Proxy.WiimoteState();
            global::WiimoteLib.WiimoteState from = ((global::WiimoteLib.WiimoteState)(transformFrom));
            global::WiimoteLib.AccelCalibrationInfo tmp = from.AccelCalibrationInfo;
            target.AccelCalibrationInfo = ((global::WiimoteLib.Proxy.AccelCalibrationInfo)(WiimoteLib_AccelCalibrationInfo_TO_WiimoteLib_Proxy_AccelCalibrationInfo(tmp)));
            global::WiimoteLib.AccelState tmp0 = from.AccelState;
            target.AccelState = ((global::WiimoteLib.Proxy.AccelState)(WiimoteLib_AccelState_TO_WiimoteLib_Proxy_AccelState(tmp0)));
            global::WiimoteLib.ButtonState tmp1 = from.ButtonState;
            target.ButtonState = ((global::WiimoteLib.Proxy.ButtonState)(WiimoteLib_ButtonState_TO_WiimoteLib_Proxy_ButtonState(tmp1)));
            global::WiimoteLib.IRState tmp2 = from.IRState;
            target.IRState = ((global::WiimoteLib.Proxy.IRState)(WiimoteLib_IRState_TO_WiimoteLib_Proxy_IRState(tmp2)));
            target.BatteryRaw = from.BatteryRaw;
            target.Battery = from.Battery;
            target.Rumble = from.Rumble;
            target.Extension = from.Extension;
            target.ExtensionType = ((global::WiimoteLib.Proxy.ExtensionType)(((long)(from.ExtensionType))));
            global::WiimoteLib.NunchukState tmp3 = from.NunchukState;
            target.NunchukState = ((global::WiimoteLib.Proxy.NunchukState)(WiimoteLib_NunchukState_TO_WiimoteLib_Proxy_NunchukState(tmp3)));
            global::WiimoteLib.ClassicControllerState tmp4 = from.ClassicControllerState;
            target.ClassicControllerState = ((global::WiimoteLib.Proxy.ClassicControllerState)(WiimoteLib_ClassicControllerState_TO_WiimoteLib_Proxy_ClassicControllerState(tmp4)));
            global::WiimoteLib.GuitarState tmp5 = from.GuitarState;
            target.GuitarState = ((global::WiimoteLib.Proxy.GuitarState)(WiimoteLib_GuitarState_TO_WiimoteLib_Proxy_GuitarState(tmp5)));
            global::WiimoteLib.DrumsState tmp6 = from.DrumsState;
            target.DrumsState = ((global::WiimoteLib.Proxy.DrumsState)(WiimoteLib_DrumsState_TO_WiimoteLib_Proxy_DrumsState(tmp6)));
            global::WiimoteLib.LEDState tmp7 = from.LEDState;
            target.LEDState = ((global::WiimoteLib.Proxy.LEDState)(WiimoteLib_LEDState_TO_WiimoteLib_Proxy_LEDState(tmp7)));
            return target;
        }
        
        public static object WiimoteLib_Proxy_AccelCalibrationInfo_TO_WiimoteLib_AccelCalibrationInfo(object transformFrom) {
            global::WiimoteLib.AccelCalibrationInfo target = new global::WiimoteLib.AccelCalibrationInfo();
            global::WiimoteLib.Proxy.AccelCalibrationInfo from = ((global::WiimoteLib.Proxy.AccelCalibrationInfo)(transformFrom));
            target.X0 = from.X0;
            target.Y0 = from.Y0;
            target.Z0 = from.Z0;
            target.XG = from.XG;
            target.YG = from.YG;
            target.ZG = from.ZG;
            return target;
        }
        
        public static object WiimoteLib_AccelCalibrationInfo_TO_WiimoteLib_Proxy_AccelCalibrationInfo(object transformFrom) {
            global::WiimoteLib.Proxy.AccelCalibrationInfo target = new global::WiimoteLib.Proxy.AccelCalibrationInfo();
            global::WiimoteLib.AccelCalibrationInfo from = ((global::WiimoteLib.AccelCalibrationInfo)(transformFrom));
            target.X0 = from.X0;
            target.Y0 = from.Y0;
            target.Z0 = from.Z0;
            target.XG = from.XG;
            target.YG = from.YG;
            target.ZG = from.ZG;
            return target;
        }
        
        public static object WiimoteLib_Proxy_AccelState_TO_WiimoteLib_AccelState(object transformFrom) {
            global::WiimoteLib.AccelState target = new global::WiimoteLib.AccelState();
            global::WiimoteLib.Proxy.AccelState from = ((global::WiimoteLib.Proxy.AccelState)(transformFrom));
            target.RawValues = ((global::WiimoteLib.Point3)(WiimoteLib_Proxy_Point3_TO_WiimoteLib_Point3(from.RawValues)));
            target.Values = ((global::WiimoteLib.Point3F)(WiimoteLib_Proxy_Point3F_TO_WiimoteLib_Point3F(from.Values)));
            return target;
        }
        
        public static object WiimoteLib_AccelState_TO_WiimoteLib_Proxy_AccelState(object transformFrom) {
            global::WiimoteLib.Proxy.AccelState target = new global::WiimoteLib.Proxy.AccelState();
            global::WiimoteLib.AccelState from = ((global::WiimoteLib.AccelState)(transformFrom));
            global::WiimoteLib.Point3 tmp = from.RawValues;
            target.RawValues = ((global::WiimoteLib.Proxy.Point3)(WiimoteLib_Point3_TO_WiimoteLib_Proxy_Point3(tmp)));
            global::WiimoteLib.Point3F tmp0 = from.Values;
            target.Values = ((global::WiimoteLib.Proxy.Point3F)(WiimoteLib_Point3F_TO_WiimoteLib_Proxy_Point3F(tmp0)));
            return target;
        }
        
        public static object WiimoteLib_Proxy_Point3_TO_WiimoteLib_Point3(object transformFrom) {
            global::WiimoteLib.Point3 target = new global::WiimoteLib.Point3();
            global::WiimoteLib.Proxy.Point3 from = ((global::WiimoteLib.Proxy.Point3)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            return target;
        }
        
        public static object WiimoteLib_Point3_TO_WiimoteLib_Proxy_Point3(object transformFrom) {
            global::WiimoteLib.Proxy.Point3 target = new global::WiimoteLib.Proxy.Point3();
            global::WiimoteLib.Point3 from = ((global::WiimoteLib.Point3)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            return target;
        }
        
        public static object WiimoteLib_Proxy_Point3F_TO_WiimoteLib_Point3F(object transformFrom) {
            global::WiimoteLib.Point3F target = new global::WiimoteLib.Point3F();
            global::WiimoteLib.Proxy.Point3F from = ((global::WiimoteLib.Proxy.Point3F)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            return target;
        }
        
        public static object WiimoteLib_Point3F_TO_WiimoteLib_Proxy_Point3F(object transformFrom) {
            global::WiimoteLib.Proxy.Point3F target = new global::WiimoteLib.Proxy.Point3F();
            global::WiimoteLib.Point3F from = ((global::WiimoteLib.Point3F)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            return target;
        }
        
        public static object WiimoteLib_Proxy_ButtonState_TO_WiimoteLib_ButtonState(object transformFrom) {
            global::WiimoteLib.ButtonState target = new global::WiimoteLib.ButtonState();
            global::WiimoteLib.Proxy.ButtonState from = ((global::WiimoteLib.Proxy.ButtonState)(transformFrom));
            target.A = from.A;
            target.B = from.B;
            target.Plus = from.Plus;
            target.Home = from.Home;
            target.Minus = from.Minus;
            target.One = from.One;
            target.Two = from.Two;
            target.Up = from.Up;
            target.Down = from.Down;
            target.Left = from.Left;
            target.Right = from.Right;
            return target;
        }
        
        public static object WiimoteLib_ButtonState_TO_WiimoteLib_Proxy_ButtonState(object transformFrom) {
            global::WiimoteLib.Proxy.ButtonState target = new global::WiimoteLib.Proxy.ButtonState();
            global::WiimoteLib.ButtonState from = ((global::WiimoteLib.ButtonState)(transformFrom));
            target.A = from.A;
            target.B = from.B;
            target.Plus = from.Plus;
            target.Home = from.Home;
            target.Minus = from.Minus;
            target.One = from.One;
            target.Two = from.Two;
            target.Up = from.Up;
            target.Down = from.Down;
            target.Left = from.Left;
            target.Right = from.Right;
            return target;
        }
        
        public static object WiimoteLib_Proxy_IRState_TO_WiimoteLib_IRState(object transformFrom) {
            global::WiimoteLib.IRState target = new global::WiimoteLib.IRState();
            global::WiimoteLib.Proxy.IRState from = ((global::WiimoteLib.Proxy.IRState)(transformFrom));
            target.Mode = ((global::WiimoteLib.IRMode)(((byte)(from.Mode))));
            if ((from.IRSensors != null)) {
                int count = from.IRSensors.Length;
                global::WiimoteLib.IRSensor[] tmp = new global::WiimoteLib.IRSensor[count];
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::WiimoteLib.IRSensor tmp0 = default(global::WiimoteLib.IRSensor);
                    tmp0 = ((global::WiimoteLib.IRSensor)(WiimoteLib_Proxy_IRSensor_TO_WiimoteLib_IRSensor(from.IRSensors[index])));
                    tmp[index] = tmp0;
                }
                target.IRSensors = tmp;
            }
            else {
                target.IRSensors = null;
            }
            target.RawMidpoint = ((global::WiimoteLib.Point)(WiimoteLib_Proxy_Point_TO_WiimoteLib_Point(from.RawMidpoint)));
            target.Midpoint = ((global::WiimoteLib.PointF)(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(from.Midpoint)));
            return target;
        }
        
        public static object WiimoteLib_IRState_TO_WiimoteLib_Proxy_IRState(object transformFrom) {
            global::WiimoteLib.Proxy.IRState target = new global::WiimoteLib.Proxy.IRState();
            global::WiimoteLib.IRState from = ((global::WiimoteLib.IRState)(transformFrom));
            target.Mode = ((global::WiimoteLib.Proxy.IRMode)(((byte)(from.Mode))));
            WiimoteLib.IRSensor[] tmp = from.IRSensors;
            if ((tmp != null)) {
                int count = tmp.Length;
                global::WiimoteLib.Proxy.IRSensor[] tmp0 = new global::WiimoteLib.Proxy.IRSensor[count];
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::WiimoteLib.Proxy.IRSensor tmp1 = default(global::WiimoteLib.Proxy.IRSensor);
                    global::WiimoteLib.IRSensor tmp2 = tmp[index];
                    tmp1 = ((global::WiimoteLib.Proxy.IRSensor)(WiimoteLib_IRSensor_TO_WiimoteLib_Proxy_IRSensor(tmp2)));
                    tmp0[index] = tmp1;
                }
                target.IRSensors = tmp0;
            }
            global::WiimoteLib.Point tmp3 = from.RawMidpoint;
            target.RawMidpoint = ((global::WiimoteLib.Proxy.Point)(WiimoteLib_Point_TO_WiimoteLib_Proxy_Point(tmp3)));
            global::WiimoteLib.PointF tmp4 = from.Midpoint;
            target.Midpoint = ((global::WiimoteLib.Proxy.PointF)(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(tmp4)));
            return target;
        }
        
        public static object WiimoteLib_Proxy_IRSensor_TO_WiimoteLib_IRSensor(object transformFrom) {
            global::WiimoteLib.IRSensor target = new global::WiimoteLib.IRSensor();
            global::WiimoteLib.Proxy.IRSensor from = ((global::WiimoteLib.Proxy.IRSensor)(transformFrom));
            target.RawPosition = ((global::WiimoteLib.Point)(WiimoteLib_Proxy_Point_TO_WiimoteLib_Point(from.RawPosition)));
            target.Position = ((global::WiimoteLib.PointF)(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(from.Position)));
            target.Size = from.Size;
            target.Found = from.Found;
            return target;
        }
        
        public static object WiimoteLib_IRSensor_TO_WiimoteLib_Proxy_IRSensor(object transformFrom) {
            global::WiimoteLib.Proxy.IRSensor target = new global::WiimoteLib.Proxy.IRSensor();
            global::WiimoteLib.IRSensor from = ((global::WiimoteLib.IRSensor)(transformFrom));
            global::WiimoteLib.Point tmp = from.RawPosition;
            target.RawPosition = ((global::WiimoteLib.Proxy.Point)(WiimoteLib_Point_TO_WiimoteLib_Proxy_Point(tmp)));
            global::WiimoteLib.PointF tmp0 = from.Position;
            target.Position = ((global::WiimoteLib.Proxy.PointF)(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(tmp0)));
            target.Size = from.Size;
            target.Found = from.Found;
            return target;
        }
        
        public static object WiimoteLib_Proxy_Point_TO_WiimoteLib_Point(object transformFrom) {
            global::WiimoteLib.Point target = new global::WiimoteLib.Point();
            global::WiimoteLib.Proxy.Point from = ((global::WiimoteLib.Proxy.Point)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            return target;
        }
        
        public static object WiimoteLib_Point_TO_WiimoteLib_Proxy_Point(object transformFrom) {
            global::WiimoteLib.Proxy.Point target = new global::WiimoteLib.Proxy.Point();
            global::WiimoteLib.Point from = ((global::WiimoteLib.Point)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            return target;
        }
        
        public static object WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(object transformFrom) {
            global::WiimoteLib.PointF target = new global::WiimoteLib.PointF();
            global::WiimoteLib.Proxy.PointF from = ((global::WiimoteLib.Proxy.PointF)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            return target;
        }
        
        public static object WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(object transformFrom) {
            global::WiimoteLib.Proxy.PointF target = new global::WiimoteLib.Proxy.PointF();
            global::WiimoteLib.PointF from = ((global::WiimoteLib.PointF)(transformFrom));
            target.X = from.X;
            target.Y = from.Y;
            return target;
        }
        
        public static object WiimoteLib_Proxy_NunchukState_TO_WiimoteLib_NunchukState(object transformFrom) {
            global::WiimoteLib.NunchukState target = new global::WiimoteLib.NunchukState();
            global::WiimoteLib.Proxy.NunchukState from = ((global::WiimoteLib.Proxy.NunchukState)(transformFrom));
            target.CalibrationInfo = ((global::WiimoteLib.NunchukCalibrationInfo)(WiimoteLib_Proxy_NunchukCalibrationInfo_TO_WiimoteLib_NunchukCalibrationInfo(from.CalibrationInfo)));
            target.AccelState = ((global::WiimoteLib.AccelState)(WiimoteLib_Proxy_AccelState_TO_WiimoteLib_AccelState(from.AccelState)));
            target.RawJoystick = ((global::WiimoteLib.Point)(WiimoteLib_Proxy_Point_TO_WiimoteLib_Point(from.RawJoystick)));
            target.Joystick = ((global::WiimoteLib.PointF)(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(from.Joystick)));
            target.C = from.C;
            target.Z = from.Z;
            return target;
        }
        
        public static object WiimoteLib_NunchukState_TO_WiimoteLib_Proxy_NunchukState(object transformFrom) {
            global::WiimoteLib.Proxy.NunchukState target = new global::WiimoteLib.Proxy.NunchukState();
            global::WiimoteLib.NunchukState from = ((global::WiimoteLib.NunchukState)(transformFrom));
            global::WiimoteLib.NunchukCalibrationInfo tmp = from.CalibrationInfo;
            target.CalibrationInfo = ((global::WiimoteLib.Proxy.NunchukCalibrationInfo)(WiimoteLib_NunchukCalibrationInfo_TO_WiimoteLib_Proxy_NunchukCalibrationInfo(tmp)));
            global::WiimoteLib.AccelState tmp0 = from.AccelState;
            target.AccelState = ((global::WiimoteLib.Proxy.AccelState)(WiimoteLib_AccelState_TO_WiimoteLib_Proxy_AccelState(tmp0)));
            global::WiimoteLib.Point tmp1 = from.RawJoystick;
            target.RawJoystick = ((global::WiimoteLib.Proxy.Point)(WiimoteLib_Point_TO_WiimoteLib_Proxy_Point(tmp1)));
            global::WiimoteLib.PointF tmp2 = from.Joystick;
            target.Joystick = ((global::WiimoteLib.Proxy.PointF)(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(tmp2)));
            target.C = from.C;
            target.Z = from.Z;
            return target;
        }
        
        public static object WiimoteLib_Proxy_NunchukCalibrationInfo_TO_WiimoteLib_NunchukCalibrationInfo(object transformFrom) {
            global::WiimoteLib.NunchukCalibrationInfo target = new global::WiimoteLib.NunchukCalibrationInfo();
            global::WiimoteLib.Proxy.NunchukCalibrationInfo from = ((global::WiimoteLib.Proxy.NunchukCalibrationInfo)(transformFrom));
            target.MinX = from.MinX;
            target.MidX = from.MidX;
            target.MaxX = from.MaxX;
            target.MinY = from.MinY;
            target.MidY = from.MidY;
            target.MaxY = from.MaxY;
            return target;
        }
        
        public static object WiimoteLib_NunchukCalibrationInfo_TO_WiimoteLib_Proxy_NunchukCalibrationInfo(object transformFrom) {
            global::WiimoteLib.Proxy.NunchukCalibrationInfo target = new global::WiimoteLib.Proxy.NunchukCalibrationInfo();
            global::WiimoteLib.NunchukCalibrationInfo from = ((global::WiimoteLib.NunchukCalibrationInfo)(transformFrom));
            target.MinX = from.MinX;
            target.MidX = from.MidX;
            target.MaxX = from.MaxX;
            target.MinY = from.MinY;
            target.MidY = from.MidY;
            target.MaxY = from.MaxY;
            return target;
        }
        
        public static object WiimoteLib_Proxy_ClassicControllerState_TO_WiimoteLib_ClassicControllerState(object transformFrom) {
            global::WiimoteLib.ClassicControllerState target = new global::WiimoteLib.ClassicControllerState();
            global::WiimoteLib.Proxy.ClassicControllerState from = ((global::WiimoteLib.Proxy.ClassicControllerState)(transformFrom));
            target.CalibrationInfo = ((global::WiimoteLib.ClassicControllerCalibrationInfo)(WiimoteLib_Proxy_ClassicControllerCalibrationInfo_TO_WiimoteLib_ClassicControllerCalibrationInfo(from.CalibrationInfo)));
            target.ButtonState = ((global::WiimoteLib.ClassicControllerButtonState)(WiimoteLib_Proxy_ClassicControllerButtonState_TO_WiimoteLib_ClassicControllerButtonState(from.ButtonState)));
            target.RawJoystickL = ((global::WiimoteLib.Point)(WiimoteLib_Proxy_Point_TO_WiimoteLib_Point(from.RawJoystickL)));
            target.RawJoystickR = ((global::WiimoteLib.Point)(WiimoteLib_Proxy_Point_TO_WiimoteLib_Point(from.RawJoystickR)));
            target.JoystickL = ((global::WiimoteLib.PointF)(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(from.JoystickL)));
            target.JoystickR = ((global::WiimoteLib.PointF)(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(from.JoystickR)));
            target.RawTriggerL = from.RawTriggerL;
            target.RawTriggerR = from.RawTriggerR;
            target.TriggerL = from.TriggerL;
            target.TriggerR = from.TriggerR;
            return target;
        }
        
        public static object WiimoteLib_ClassicControllerState_TO_WiimoteLib_Proxy_ClassicControllerState(object transformFrom) {
            global::WiimoteLib.Proxy.ClassicControllerState target = new global::WiimoteLib.Proxy.ClassicControllerState();
            global::WiimoteLib.ClassicControllerState from = ((global::WiimoteLib.ClassicControllerState)(transformFrom));
            global::WiimoteLib.ClassicControllerCalibrationInfo tmp = from.CalibrationInfo;
            target.CalibrationInfo = ((global::WiimoteLib.Proxy.ClassicControllerCalibrationInfo)(WiimoteLib_ClassicControllerCalibrationInfo_TO_WiimoteLib_Proxy_ClassicControllerCalibrationInfo(tmp)));
            global::WiimoteLib.ClassicControllerButtonState tmp0 = from.ButtonState;
            target.ButtonState = ((global::WiimoteLib.Proxy.ClassicControllerButtonState)(WiimoteLib_ClassicControllerButtonState_TO_WiimoteLib_Proxy_ClassicControllerButtonState(tmp0)));
            global::WiimoteLib.Point tmp1 = from.RawJoystickL;
            target.RawJoystickL = ((global::WiimoteLib.Proxy.Point)(WiimoteLib_Point_TO_WiimoteLib_Proxy_Point(tmp1)));
            global::WiimoteLib.Point tmp2 = from.RawJoystickR;
            target.RawJoystickR = ((global::WiimoteLib.Proxy.Point)(WiimoteLib_Point_TO_WiimoteLib_Proxy_Point(tmp2)));
            global::WiimoteLib.PointF tmp3 = from.JoystickL;
            target.JoystickL = ((global::WiimoteLib.Proxy.PointF)(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(tmp3)));
            global::WiimoteLib.PointF tmp4 = from.JoystickR;
            target.JoystickR = ((global::WiimoteLib.Proxy.PointF)(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(tmp4)));
            target.RawTriggerL = from.RawTriggerL;
            target.RawTriggerR = from.RawTriggerR;
            target.TriggerL = from.TriggerL;
            target.TriggerR = from.TriggerR;
            return target;
        }
        
        public static object WiimoteLib_Proxy_ClassicControllerCalibrationInfo_TO_WiimoteLib_ClassicControllerCalibrationInfo(object transformFrom) {
            global::WiimoteLib.ClassicControllerCalibrationInfo target = new global::WiimoteLib.ClassicControllerCalibrationInfo();
            global::WiimoteLib.Proxy.ClassicControllerCalibrationInfo from = ((global::WiimoteLib.Proxy.ClassicControllerCalibrationInfo)(transformFrom));
            target.MinXL = from.MinXL;
            target.MidXL = from.MidXL;
            target.MaxXL = from.MaxXL;
            target.MinYL = from.MinYL;
            target.MidYL = from.MidYL;
            target.MaxYL = from.MaxYL;
            target.MinXR = from.MinXR;
            target.MidXR = from.MidXR;
            target.MaxXR = from.MaxXR;
            target.MinYR = from.MinYR;
            target.MidYR = from.MidYR;
            target.MaxYR = from.MaxYR;
            target.MinTriggerL = from.MinTriggerL;
            target.MaxTriggerL = from.MaxTriggerL;
            target.MinTriggerR = from.MinTriggerR;
            target.MaxTriggerR = from.MaxTriggerR;
            return target;
        }
        
        public static object WiimoteLib_ClassicControllerCalibrationInfo_TO_WiimoteLib_Proxy_ClassicControllerCalibrationInfo(object transformFrom) {
            global::WiimoteLib.Proxy.ClassicControllerCalibrationInfo target = new global::WiimoteLib.Proxy.ClassicControllerCalibrationInfo();
            global::WiimoteLib.ClassicControllerCalibrationInfo from = ((global::WiimoteLib.ClassicControllerCalibrationInfo)(transformFrom));
            target.MinXL = from.MinXL;
            target.MidXL = from.MidXL;
            target.MaxXL = from.MaxXL;
            target.MinYL = from.MinYL;
            target.MidYL = from.MidYL;
            target.MaxYL = from.MaxYL;
            target.MinXR = from.MinXR;
            target.MidXR = from.MidXR;
            target.MaxXR = from.MaxXR;
            target.MinYR = from.MinYR;
            target.MidYR = from.MidYR;
            target.MaxYR = from.MaxYR;
            target.MinTriggerL = from.MinTriggerL;
            target.MaxTriggerL = from.MaxTriggerL;
            target.MinTriggerR = from.MinTriggerR;
            target.MaxTriggerR = from.MaxTriggerR;
            return target;
        }
        
        public static object WiimoteLib_Proxy_ClassicControllerButtonState_TO_WiimoteLib_ClassicControllerButtonState(object transformFrom) {
            global::WiimoteLib.ClassicControllerButtonState target = new global::WiimoteLib.ClassicControllerButtonState();
            global::WiimoteLib.Proxy.ClassicControllerButtonState from = ((global::WiimoteLib.Proxy.ClassicControllerButtonState)(transformFrom));
            target.A = from.A;
            target.B = from.B;
            target.Plus = from.Plus;
            target.Home = from.Home;
            target.Minus = from.Minus;
            target.Up = from.Up;
            target.Down = from.Down;
            target.Left = from.Left;
            target.Right = from.Right;
            target.X = from.X;
            target.Y = from.Y;
            target.ZL = from.ZL;
            target.ZR = from.ZR;
            target.TriggerL = from.TriggerL;
            target.TriggerR = from.TriggerR;
            return target;
        }
        
        public static object WiimoteLib_ClassicControllerButtonState_TO_WiimoteLib_Proxy_ClassicControllerButtonState(object transformFrom) {
            global::WiimoteLib.Proxy.ClassicControllerButtonState target = new global::WiimoteLib.Proxy.ClassicControllerButtonState();
            global::WiimoteLib.ClassicControllerButtonState from = ((global::WiimoteLib.ClassicControllerButtonState)(transformFrom));
            target.A = from.A;
            target.B = from.B;
            target.Plus = from.Plus;
            target.Home = from.Home;
            target.Minus = from.Minus;
            target.Up = from.Up;
            target.Down = from.Down;
            target.Left = from.Left;
            target.Right = from.Right;
            target.X = from.X;
            target.Y = from.Y;
            target.ZL = from.ZL;
            target.ZR = from.ZR;
            target.TriggerL = from.TriggerL;
            target.TriggerR = from.TriggerR;
            return target;
        }
        
        public static object WiimoteLib_Proxy_GuitarState_TO_WiimoteLib_GuitarState(object transformFrom) {
            global::WiimoteLib.GuitarState target = new global::WiimoteLib.GuitarState();
            global::WiimoteLib.Proxy.GuitarState from = ((global::WiimoteLib.Proxy.GuitarState)(transformFrom));
            target.GuitarType = ((global::WiimoteLib.GuitarType)(((int)(from.GuitarType))));
            target.ButtonState = ((global::WiimoteLib.GuitarButtonState)(WiimoteLib_Proxy_GuitarButtonState_TO_WiimoteLib_GuitarButtonState(from.ButtonState)));
            target.FretButtonState = ((global::WiimoteLib.GuitarFretButtonState)(WiimoteLib_Proxy_GuitarFretButtonState_TO_WiimoteLib_GuitarFretButtonState(from.FretButtonState)));
            target.TouchbarState = ((global::WiimoteLib.GuitarFretButtonState)(WiimoteLib_Proxy_GuitarFretButtonState_TO_WiimoteLib_GuitarFretButtonState(from.TouchbarState)));
            target.RawJoystick = ((global::WiimoteLib.Point)(WiimoteLib_Proxy_Point_TO_WiimoteLib_Point(from.RawJoystick)));
            target.Joystick = ((global::WiimoteLib.PointF)(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(from.Joystick)));
            target.RawWhammyBar = from.RawWhammyBar;
            target.WhammyBar = from.WhammyBar;
            return target;
        }
        
        public static object WiimoteLib_GuitarState_TO_WiimoteLib_Proxy_GuitarState(object transformFrom) {
            global::WiimoteLib.Proxy.GuitarState target = new global::WiimoteLib.Proxy.GuitarState();
            global::WiimoteLib.GuitarState from = ((global::WiimoteLib.GuitarState)(transformFrom));
            target.GuitarType = ((global::WiimoteLib.Proxy.GuitarType)(((int)(from.GuitarType))));
            global::WiimoteLib.GuitarButtonState tmp = from.ButtonState;
            target.ButtonState = ((global::WiimoteLib.Proxy.GuitarButtonState)(WiimoteLib_GuitarButtonState_TO_WiimoteLib_Proxy_GuitarButtonState(tmp)));
            global::WiimoteLib.GuitarFretButtonState tmp0 = from.FretButtonState;
            target.FretButtonState = ((global::WiimoteLib.Proxy.GuitarFretButtonState)(WiimoteLib_GuitarFretButtonState_TO_WiimoteLib_Proxy_GuitarFretButtonState(tmp0)));
            global::WiimoteLib.GuitarFretButtonState tmp1 = from.TouchbarState;
            target.TouchbarState = ((global::WiimoteLib.Proxy.GuitarFretButtonState)(WiimoteLib_GuitarFretButtonState_TO_WiimoteLib_Proxy_GuitarFretButtonState(tmp1)));
            global::WiimoteLib.Point tmp2 = from.RawJoystick;
            target.RawJoystick = ((global::WiimoteLib.Proxy.Point)(WiimoteLib_Point_TO_WiimoteLib_Proxy_Point(tmp2)));
            global::WiimoteLib.PointF tmp3 = from.Joystick;
            target.Joystick = ((global::WiimoteLib.Proxy.PointF)(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(tmp3)));
            target.RawWhammyBar = from.RawWhammyBar;
            target.WhammyBar = from.WhammyBar;
            return target;
        }
        
        public static object WiimoteLib_Proxy_GuitarButtonState_TO_WiimoteLib_GuitarButtonState(object transformFrom) {
            global::WiimoteLib.GuitarButtonState target = new global::WiimoteLib.GuitarButtonState();
            global::WiimoteLib.Proxy.GuitarButtonState from = ((global::WiimoteLib.Proxy.GuitarButtonState)(transformFrom));
            target.StrumUp = from.StrumUp;
            target.StrumDown = from.StrumDown;
            target.Minus = from.Minus;
            target.Plus = from.Plus;
            return target;
        }
        
        public static object WiimoteLib_GuitarButtonState_TO_WiimoteLib_Proxy_GuitarButtonState(object transformFrom) {
            global::WiimoteLib.Proxy.GuitarButtonState target = new global::WiimoteLib.Proxy.GuitarButtonState();
            global::WiimoteLib.GuitarButtonState from = ((global::WiimoteLib.GuitarButtonState)(transformFrom));
            target.StrumUp = from.StrumUp;
            target.StrumDown = from.StrumDown;
            target.Minus = from.Minus;
            target.Plus = from.Plus;
            return target;
        }
        
        public static object WiimoteLib_Proxy_GuitarFretButtonState_TO_WiimoteLib_GuitarFretButtonState(object transformFrom) {
            global::WiimoteLib.GuitarFretButtonState target = new global::WiimoteLib.GuitarFretButtonState();
            global::WiimoteLib.Proxy.GuitarFretButtonState from = ((global::WiimoteLib.Proxy.GuitarFretButtonState)(transformFrom));
            target.Green = from.Green;
            target.Red = from.Red;
            target.Yellow = from.Yellow;
            target.Blue = from.Blue;
            target.Orange = from.Orange;
            return target;
        }
        
        public static object WiimoteLib_GuitarFretButtonState_TO_WiimoteLib_Proxy_GuitarFretButtonState(object transformFrom) {
            global::WiimoteLib.Proxy.GuitarFretButtonState target = new global::WiimoteLib.Proxy.GuitarFretButtonState();
            global::WiimoteLib.GuitarFretButtonState from = ((global::WiimoteLib.GuitarFretButtonState)(transformFrom));
            target.Green = from.Green;
            target.Red = from.Red;
            target.Yellow = from.Yellow;
            target.Blue = from.Blue;
            target.Orange = from.Orange;
            return target;
        }
        
        private static global::WiimoteLib.Proxy.DrumsState _cachedInstance0 = new global::WiimoteLib.Proxy.DrumsState();
        
        private static global::WiimoteLib.DrumsState _cachedInstance = new global::WiimoteLib.DrumsState();
        
        public static object WiimoteLib_Proxy_DrumsState_TO_WiimoteLib_DrumsState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object WiimoteLib_DrumsState_TO_WiimoteLib_Proxy_DrumsState(object transformFrom) {
            return _cachedInstance0;
        }
        
        public static object WiimoteLib_Proxy_LEDState_TO_WiimoteLib_LEDState(object transformFrom) {
            global::WiimoteLib.LEDState target = new global::WiimoteLib.LEDState();
            global::WiimoteLib.Proxy.LEDState from = ((global::WiimoteLib.Proxy.LEDState)(transformFrom));
            target.LED1 = from.LED1;
            target.LED2 = from.LED2;
            target.LED3 = from.LED3;
            target.LED4 = from.LED4;
            return target;
        }
        
        public static object WiimoteLib_LEDState_TO_WiimoteLib_Proxy_LEDState(object transformFrom) {
            global::WiimoteLib.Proxy.LEDState target = new global::WiimoteLib.Proxy.LEDState();
            global::WiimoteLib.LEDState from = ((global::WiimoteLib.LEDState)(transformFrom));
            target.LED1 = from.LED1;
            target.LED2 = from.LED2;
            target.LED3 = from.LED3;
            target.LED4 = from.LED4;
            return target;
        }
        
        public static object WiimoteLib_Proxy_RumbleRequest_TO_WiimoteLib_RumbleRequest(object transformFrom) {
            global::WiimoteLib.RumbleRequest target = new global::WiimoteLib.RumbleRequest();
            global::WiimoteLib.Proxy.RumbleRequest from = ((global::WiimoteLib.Proxy.RumbleRequest)(transformFrom));
            target.Rumble = from.Rumble;
            return target;
        }
        
        public static object WiimoteLib_RumbleRequest_TO_WiimoteLib_Proxy_RumbleRequest(object transformFrom) {
            global::WiimoteLib.Proxy.RumbleRequest target = new global::WiimoteLib.Proxy.RumbleRequest();
            global::WiimoteLib.RumbleRequest from = ((global::WiimoteLib.RumbleRequest)(transformFrom));
            target.Rumble = from.Rumble;
            return target;
        }
        
        public static object WiimoteLib_Proxy_BalanceBoardState_TO_WiimoteLib_BalanceBoardState(object transformFrom) {
            global::WiimoteLib.BalanceBoardState target = new global::WiimoteLib.BalanceBoardState();
            global::WiimoteLib.Proxy.BalanceBoardState from = ((global::WiimoteLib.Proxy.BalanceBoardState)(transformFrom));
            target.CalibrationInfo = ((global::WiimoteLib.BalanceBoardCalibrationInfo)(WiimoteLib_Proxy_BalanceBoardCalibrationInfo_TO_WiimoteLib_BalanceBoardCalibrationInfo(from.CalibrationInfo)));
            target.SensorValuesRaw = ((global::WiimoteLib.BalanceBoardSensors)(WiimoteLib_Proxy_BalanceBoardSensors_TO_WiimoteLib_BalanceBoardSensors(from.SensorValuesRaw)));
            target.SensorValuesKg = ((global::WiimoteLib.BalanceBoardSensorsF)(WiimoteLib_Proxy_BalanceBoardSensorsF_TO_WiimoteLib_BalanceBoardSensorsF(from.SensorValuesKg)));
            target.SensorValuesLb = ((global::WiimoteLib.BalanceBoardSensorsF)(WiimoteLib_Proxy_BalanceBoardSensorsF_TO_WiimoteLib_BalanceBoardSensorsF(from.SensorValuesLb)));
            target.WeightKg = from.WeightKg;
            target.WeightLb = from.WeightLb;
            target.CenterOfGravity = ((global::WiimoteLib.PointF)(WiimoteLib_Proxy_PointF_TO_WiimoteLib_PointF(from.CenterOfGravity)));
            return target;
        }
        
        public static object WiimoteLib_BalanceBoardState_TO_WiimoteLib_Proxy_BalanceBoardState(object transformFrom) {
            global::WiimoteLib.Proxy.BalanceBoardState target = new global::WiimoteLib.Proxy.BalanceBoardState();
            global::WiimoteLib.BalanceBoardState from = ((global::WiimoteLib.BalanceBoardState)(transformFrom));
            global::WiimoteLib.BalanceBoardCalibrationInfo tmp = from.CalibrationInfo;
            target.CalibrationInfo = ((global::WiimoteLib.Proxy.BalanceBoardCalibrationInfo)(WiimoteLib_BalanceBoardCalibrationInfo_TO_WiimoteLib_Proxy_BalanceBoardCalibrationInfo(tmp)));
            global::WiimoteLib.BalanceBoardSensors tmp0 = from.SensorValuesRaw;
            target.SensorValuesRaw = ((global::WiimoteLib.Proxy.BalanceBoardSensors)(WiimoteLib_BalanceBoardSensors_TO_WiimoteLib_Proxy_BalanceBoardSensors(tmp0)));
            global::WiimoteLib.BalanceBoardSensorsF tmp1 = from.SensorValuesKg;
            target.SensorValuesKg = ((global::WiimoteLib.Proxy.BalanceBoardSensorsF)(WiimoteLib_BalanceBoardSensorsF_TO_WiimoteLib_Proxy_BalanceBoardSensorsF(tmp1)));
            global::WiimoteLib.BalanceBoardSensorsF tmp2 = from.SensorValuesLb;
            target.SensorValuesLb = ((global::WiimoteLib.Proxy.BalanceBoardSensorsF)(WiimoteLib_BalanceBoardSensorsF_TO_WiimoteLib_Proxy_BalanceBoardSensorsF(tmp2)));
            target.WeightKg = from.WeightKg;
            target.WeightLb = from.WeightLb;
            global::WiimoteLib.PointF tmp3 = from.CenterOfGravity;
            target.CenterOfGravity = ((global::WiimoteLib.Proxy.PointF)(WiimoteLib_PointF_TO_WiimoteLib_Proxy_PointF(tmp3)));
            return target;
        }
        
        public static object WiimoteLib_Proxy_BalanceBoardCalibrationInfo_TO_WiimoteLib_BalanceBoardCalibrationInfo(object transformFrom) {
            global::WiimoteLib.BalanceBoardCalibrationInfo target = new global::WiimoteLib.BalanceBoardCalibrationInfo();
            global::WiimoteLib.Proxy.BalanceBoardCalibrationInfo from = ((global::WiimoteLib.Proxy.BalanceBoardCalibrationInfo)(transformFrom));
            target.Kg0 = ((global::WiimoteLib.BalanceBoardSensors)(WiimoteLib_Proxy_BalanceBoardSensors_TO_WiimoteLib_BalanceBoardSensors(from.Kg0)));
            target.Kg17 = ((global::WiimoteLib.BalanceBoardSensors)(WiimoteLib_Proxy_BalanceBoardSensors_TO_WiimoteLib_BalanceBoardSensors(from.Kg17)));
            target.Kg34 = ((global::WiimoteLib.BalanceBoardSensors)(WiimoteLib_Proxy_BalanceBoardSensors_TO_WiimoteLib_BalanceBoardSensors(from.Kg34)));
            return target;
        }
        
        public static object WiimoteLib_BalanceBoardCalibrationInfo_TO_WiimoteLib_Proxy_BalanceBoardCalibrationInfo(object transformFrom) {
            global::WiimoteLib.Proxy.BalanceBoardCalibrationInfo target = new global::WiimoteLib.Proxy.BalanceBoardCalibrationInfo();
            global::WiimoteLib.BalanceBoardCalibrationInfo from = ((global::WiimoteLib.BalanceBoardCalibrationInfo)(transformFrom));
            global::WiimoteLib.BalanceBoardSensors tmp = from.Kg0;
            target.Kg0 = ((global::WiimoteLib.Proxy.BalanceBoardSensors)(WiimoteLib_BalanceBoardSensors_TO_WiimoteLib_Proxy_BalanceBoardSensors(tmp)));
            global::WiimoteLib.BalanceBoardSensors tmp0 = from.Kg17;
            target.Kg17 = ((global::WiimoteLib.Proxy.BalanceBoardSensors)(WiimoteLib_BalanceBoardSensors_TO_WiimoteLib_Proxy_BalanceBoardSensors(tmp0)));
            global::WiimoteLib.BalanceBoardSensors tmp1 = from.Kg34;
            target.Kg34 = ((global::WiimoteLib.Proxy.BalanceBoardSensors)(WiimoteLib_BalanceBoardSensors_TO_WiimoteLib_Proxy_BalanceBoardSensors(tmp1)));
            return target;
        }
        
        public static object WiimoteLib_Proxy_BalanceBoardSensors_TO_WiimoteLib_BalanceBoardSensors(object transformFrom) {
            global::WiimoteLib.BalanceBoardSensors target = new global::WiimoteLib.BalanceBoardSensors();
            global::WiimoteLib.Proxy.BalanceBoardSensors from = ((global::WiimoteLib.Proxy.BalanceBoardSensors)(transformFrom));
            target.TopRight = from.TopRight;
            target.TopLeft = from.TopLeft;
            target.BottomRight = from.BottomRight;
            target.BottomLeft = from.BottomLeft;
            return target;
        }
        
        public static object WiimoteLib_BalanceBoardSensors_TO_WiimoteLib_Proxy_BalanceBoardSensors(object transformFrom) {
            global::WiimoteLib.Proxy.BalanceBoardSensors target = new global::WiimoteLib.Proxy.BalanceBoardSensors();
            global::WiimoteLib.BalanceBoardSensors from = ((global::WiimoteLib.BalanceBoardSensors)(transformFrom));
            target.TopRight = from.TopRight;
            target.TopLeft = from.TopLeft;
            target.BottomRight = from.BottomRight;
            target.BottomLeft = from.BottomLeft;
            return target;
        }
        
        public static object WiimoteLib_Proxy_BalanceBoardSensorsF_TO_WiimoteLib_BalanceBoardSensorsF(object transformFrom) {
            global::WiimoteLib.BalanceBoardSensorsF target = new global::WiimoteLib.BalanceBoardSensorsF();
            global::WiimoteLib.Proxy.BalanceBoardSensorsF from = ((global::WiimoteLib.Proxy.BalanceBoardSensorsF)(transformFrom));
            target.TopRight = from.TopRight;
            target.TopLeft = from.TopLeft;
            target.BottomRight = from.BottomRight;
            target.BottomLeft = from.BottomLeft;
            return target;
        }
        
        public static object WiimoteLib_BalanceBoardSensorsF_TO_WiimoteLib_Proxy_BalanceBoardSensorsF(object transformFrom) {
            global::WiimoteLib.Proxy.BalanceBoardSensorsF target = new global::WiimoteLib.Proxy.BalanceBoardSensorsF();
            global::WiimoteLib.BalanceBoardSensorsF from = ((global::WiimoteLib.BalanceBoardSensorsF)(transformFrom));
            target.TopRight = from.TopRight;
            target.TopLeft = from.TopLeft;
            target.BottomRight = from.BottomRight;
            target.BottomLeft = from.BottomLeft;
            return target;
        }
    }
}
