//------------------------------------------------------------------------------
// AssemblyInfo.cs
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------
using Microsoft.Dss.Core.Attributes;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: ServiceDeclaration(DssServiceDeclaration.ServiceBehavior)]
[assembly: interopservices.ComVisible(false)]

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("WiimoteMSRS")]
[assembly: AssemblyDescription("Microsoft Robotics Studio Service for the Nintendo Wiimote")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Brian Peek (www.brianpeek.com)")]
[assembly: AssemblyProduct("WiimoteMSRS")]
[assembly: AssemblyCopyright("Copyright © 2008 Brian Peek (www.brianpeek.com)")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("1.5.2.0")]
[assembly: AssemblyFileVersion("1.5.2.0")]
